/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

/**
 *
 * @author caiov
 */
public class TelaMenuOpcoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuOpcoes
     */
    public TelaMenuOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonCursos = new javax.swing.JButton();
        jButtonPagamentos = new javax.swing.JButton();
        jButtonCategorias = new javax.swing.JButton();
        jButtonMatriculas = new javax.swing.JButton();
        jButtonCertificados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu de opções");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        jPanel2.setBackground(new java.awt.Color(200, 195, 195));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));

        jButtonUsuarios.setBackground(new java.awt.Color(102, 102, 102));
        jButtonUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUsuarios.setText("Usuarios");
        jButtonUsuarios.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonUsuarios.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonUsuarios.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosActionPerformed(evt);
            }
        });

        jButtonCursos.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCursos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCursos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCursos.setText("Cursos");
        jButtonCursos.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonCursos.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonCursos.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCursosActionPerformed(evt);
            }
        });

        jButtonPagamentos.setBackground(new java.awt.Color(102, 102, 102));
        jButtonPagamentos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPagamentos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPagamentos.setText("Pagamentos");
        jButtonPagamentos.setActionCommand("Aulas");
        jButtonPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagamentosActionPerformed(evt);
            }
        });

        jButtonCategorias.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCategorias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCategorias.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCategorias.setText("Categorias");
        jButtonCategorias.setActionCommand("Aulas");
        jButtonCategorias.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonCategorias.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonCategorias.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriasActionPerformed(evt);
            }
        });

        jButtonMatriculas.setBackground(new java.awt.Color(102, 102, 102));
        jButtonMatriculas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonMatriculas.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMatriculas.setText("Matriculas");
        jButtonMatriculas.setActionCommand("Aulas");
        jButtonMatriculas.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonMatriculas.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonMatriculas.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatriculasActionPerformed(evt);
            }
        });

        jButtonCertificados.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCertificados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCertificados.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCertificados.setText("Certificados");
        jButtonCertificados.setActionCommand("Aulas");
        jButtonCertificados.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonCertificados.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonCertificados.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonCertificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCertificadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPagamentos))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCertificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCertificados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCursosActionPerformed
        // TODO add your handling code here:
        TelaCursos cursos = new TelaCursos();
        cursos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCursosActionPerformed

    private void jButtonMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatriculasActionPerformed
        // TODO add your handling code here:
        TelaMatriculas matriculas = new TelaMatriculas();
        matriculas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMatriculasActionPerformed

    private void jButtonCertificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCertificadosActionPerformed
        // TODO add your handling code here:
        TelaCertificados certificados = new TelaCertificados();
        certificados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCertificadosActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        // TODO add your handling code here:
        TelaUsuarios usuarios = new TelaUsuarios();
        usuarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriasActionPerformed
        // TODO add your handling code here:
        TelaCategorias categorias = new TelaCategorias();
        categorias.setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_jButtonCategoriasActionPerformed

    private void jButtonPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagamentosActionPerformed
        // TODO add your handling code here:
        TelaPagamentos pagamentos = new TelaPagamentos();
        pagamentos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonPagamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCategorias;
    private javax.swing.JButton jButtonCertificados;
    private javax.swing.JButton jButtonCursos;
    private javax.swing.JButton jButtonMatriculas;
    private javax.swing.JButton jButtonPagamentos;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
